import React from 'react'
import type { Metadata } from 'next'
import './css/globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import ServiceWorkerRegister from '@/app/components/service-worker/ServiceWorkerRegister'

export const metadata: Metadata = {
  title: 'TailwindAdmin - Nextjs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link
          rel='icon'
          href='/tailwindadmin-nextjs/favicon.svg'
          type='image/svg+xml'
        />
        <link rel='manifest' href='/tailwindadmin-nextjs/manifest.json' />
        <meta name="theme-color" content="#5d87ff" />
      </head>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <ServiceWorkerRegister />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
